<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="392.6500" tests="25" failures="13">
  <testsuite name="Root Suite" timestamp="2022-03-10T10:28:44" tests="0" file="cypress/integration/resolver_spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test Scenario 1: DID Resolution Result overview" timestamp="2022-03-10T10:28:44" tests="5" time="30.2290" failures="1">
    <testcase name="Test Scenario 1: DID Resolution Result overview &quot;before each&quot; hook for &quot;MUST return HTTP code 200&quot;" time="0.0000" classname="&quot;before each&quot; hook for &quot;MUST return HTTP code 200&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test Scenario 1: DID Resolu...`" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test Scenario 1: DID Resolu...`
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:101:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Test Scenario 2: JSON-LD DID document" timestamp="2022-03-10T10:29:15" tests="4" time="30.2040" failures="1">
    <testcase name="Test Scenario 2: JSON-LD DID document &quot;before each&quot; hook for &quot;Should have response status 200&quot;" time="0.0000" classname="&quot;before each&quot; hook for &quot;Should have response status 200&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test Scenario 2: JSON-LD DI...`" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test Scenario 2: JSON-LD DI...`
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:134:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Test Scenario 3: Representation not supported" timestamp="2022-03-10T10:29:45" tests="1" time="30.1710" failures="1">
    <testcase name="Test Scenario 3: Representation not supported MUST return HTTP code 406" time="0.0000" classname="MUST return HTTP code 406">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:165:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Test Scenario 4: Deactivated" timestamp="2022-03-10T10:30:15" tests="3" time="90.5990" failures="3">
    <testcase name="Test Scenario 4: Deactivated MUST return HTTP code 410" time="0.0000" classname="MUST return HTTP code 410">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:179:8)]]></failure>
    </testcase>
    <testcase name="Test Scenario 4: Deactivated MUST return HTTP header Content-Type" time="0.0000" classname="MUST return HTTP header Content-Type">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:188:8)]]></failure>
    </testcase>
    <testcase name="Test Scenario 4: Deactivated JSON object MUST contain property didDocumentMetadata.deactivated = true" time="0.0000" classname="JSON object MUST contain property didDocumentMetadata.deactivated = true">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:kilt:4r6RdVMNes2eEobxyxH7aVsesUqR2X175sUAXJfo7dEWxHUS

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:197:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Test Scenario 5: Not found" timestamp="2022-03-10T10:31:46" tests="3" time="90.5980" failures="3">
    <testcase name="Test Scenario 5: Not found MUST return HTTP code 404" time="0.0000" classname="MUST return HTTP code 404">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:0000000000000000000000

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:0000000000000000000000

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:209:8)]]></failure>
    </testcase>
    <testcase name="Test Scenario 5: Not found MUST return HTTP header Content-Type with value application/ld+json;profile=&quot;https://w3id.org/did-resolution&quot;" time="0.0000" classname="MUST return HTTP header Content-Type with value application/ld+json;profile=&quot;https://w3id.org/did-resolution&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:0000000000000000000000

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:0000000000000000000000

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:218:8)]]></failure>
    </testcase>
    <testcase name="Test Scenario 5: Not found JSON object MUST contain property didResolutionMetadata.error = &quot;notFound&quot;" time="0.0000" classname="JSON object MUST contain property didResolutionMetadata.error = &quot;notFound&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:0000000000000000000000

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:sov:0000000000000000000000

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:227:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Test Scenario 6: Invalid DID" timestamp="2022-03-10T10:33:16" tests="3" time="90.5870" failures="3">
    <testcase name="Test Scenario 6: Invalid DID MUST return HTTP code 400" time="0.0000" classname="MUST return HTTP code 400">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:example_222

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:example_222

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:238:8)]]></failure>
    </testcase>
    <testcase name="Test Scenario 6: Invalid DID MUST return HTTP header Content-Type with value application/ld+json;profile=&quot;https://w3id.org/did-resolution&quot;" time="0.0000" classname="MUST return HTTP header Content-Type with value application/ld+json;profile=&quot;https://w3id.org/did-resolution&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:example_222

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:example_222

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:247:8)]]></failure>
    </testcase>
    <testcase name="Test Scenario 6: Invalid DID JSON object MUST contain property didResolutionMetadata.error = &quot;invalidDid&quot;" time="0.0000" classname="JSON object MUST contain property didResolutionMetadata.error = &quot;invalidDid&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:example_222

No response was received within the timeout.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did:example_222

No response was received within the timeout.

https://on.cypress.io/request
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:256:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Test Scenario 7: DID URLs with fragments" timestamp="2022-03-10T10:34:47" tests="6" time="30.2410" failures="1">
    <testcase name="Test Scenario 7: DID URLs with fragments &quot;before each&quot; hook for &quot;Must return HTTP code 200&quot;" time="0.0000" classname="&quot;before each&quot; hook for &quot;Must return HTTP code 200&quot;">
      <failure message="`cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did%3Asov%3AWRfXPg8dantKVubE3HX8pw%23key-1

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test Scenario 7: DID URLs w...`" type="CypressError"><![CDATA[CypressError: `cy.request()` timed out waiting `30000ms` for a response from your server.

The request we sent was:

Method: GET
URL: https://dev.uniresolver.io/1.0/identifiers/did%3Asov%3AWRfXPg8dantKVubE3HX8pw%23key-1

No response was received within the timeout.

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test Scenario 7: DID URLs w...`
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:160652:78
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at https://dev.godiddy.com/__cypress/runner/cypress_runner.js:8144:41
    at tryCatcher (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (https://dev.godiddy.com/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (https://dev.godiddy.com/__cypress/tests?p=cypress/integration/resolver_spec.js:268:8)]]></failure>
    </testcase>
  </testsuite>
</testsuites>